export const stageMessageMap: Map<number, string> = new Map([
    [0, 'Tu ojo místico aún no es capaz de ver el futuro con claridad.'],
    [1, 'La paciencia es amarga, pero sus frutos son dulces. Es el arte de la esperanza, y la compañera de la sabiduría.'],
    [2, 'La impaciencia nubla la visión del alma.'],
    [3, 'La semilla aún necesita más tiempo para florecer.'],
    [4, 'La flor no se apresura a florecer, y sin embargo, lo hace con perfección.'],
    [5, 'El río no se impacienta, y aún así, llega al mar.'],
    [6, 'La calma es el lenguaje de los sabios.'],
    [7, 'El alma paciente es como el cielo: inmenso, sereno, eterno.'],
    [8, 'Quien domina la espera, domina el universo.'],
    [9, 'El sabio no corre, camina con el viento.'],
    [10, 'Cada segundo de espera es una semilla de sabiduría.'],
    [11, 'El tiempo es un alquimista que transforma todo con paciencia.'],
    [12, 'La serenidad es la voz de los que escuchan al universo.'],
    [13, 'El árbol no se impone al sol, simplemente crece hacia él.'],
    [14, 'En el silencio de la espera, el espíritu se fortalece.'],
    [15, 'La eternidad no tiene prisa.'],
    [16, 'La impaciencia es hija del miedo; la paciencia, del amor.'],
    [17, 'En la quietud, el universo revela sus secretos.'],
    [18, 'Quien sabe esperar, ya ha comenzado a recibir.'],
    [19, 'La sabiduría florece en los jardines de la espera.'],
    [20, 'La paciencia es la llave que abre puertas invisibles.'],
    [21, 'La paciencia es un puente entre el deseo y la realización.'],
    [22, 'El universo conspira a favor de quien sabe esperar.'],
    [23, 'La paciencia es el susurro del alma que confía en el tiempo divino.'],
    [24, 'La luna no se queja por no brillar de día.'],
    [25, 'La paciencia es la fe en movimiento lento.'],
    [26, 'La espera es el templo donde se forja la voluntad.'],
    [27, 'La paciencia no es pasividad, es poder contenido.'],
    [28, 'La espera es un acto de amor hacia el destino.'],
    [29, 'El tiempo no se pierde cuando se espera con propósito.'],
    [30, 'La paciencia es el eco de la confianza en lo eterno.'],
    [31, 'La paciencia es la alquimia del corazón.'],
    [32, 'La paciencia es el arte de danzar con el ritmo del cosmos.'],
]);
